# Generated by Django 3.2.18 on 2023-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studapp', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('phy', models.FloatField()),
                ('chem', models.FloatField()),
                ('maths', models.FloatField()),
                ('cs', models.FloatField()),
                ('per', models.FloatField()),
            ],
        ),
    ]
